#!/usr/bin/env python3
#coding: utf8

import sys
import os
sys.path.append("./mk")

from glink.lang.pars import parse_file as parse_file 
from glink.lang.interpret import global_start  
from glink.lang.interpret import global_start_module_mode 

mod = global_start_module_mode('./curprj/' + 'mkscript.gl', globals(), 0)

#print(mod["applications"])
#print(mod["modules"])

#for a in mod["applications"]:
#	print(a)
#	for m in a.mlist:
#		print(m)
