#!/usr/bin/env python3
#coding: utf8

import sys
import os
sys.path.append("./mk")

a=28

from glink.lang.pars import parse_file as parse_file 
from glink.lang.interpret import global_start 

global_start('./curprj/' + 'mkscript.gl', globals(), 0)

